# Generated by Django 3.1.6 on 2021-02-10 19:44

import candidates.vpresidency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PVpresidencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.vpresidency.models.PVpresidencyModel.Pcant_url)),
            ],
            options={
                'verbose_name': 'PVpresiden',
                'verbose_name_plural': 'PVpresidency',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SVpresidencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.vpresidency.models.SVpresidencyModel.Scant_url)),
            ],
            options={
                'verbose_name': 'SVpresiden',
                'verbose_name_plural': 'SVpresidency',
                'ordering': ['id'],
            },
        ),
    ]
