# Generated by Django 3.1.6 on 2021-02-10 17:08

import candidates.presidency.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresidencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=150, verbose_name='Apellido')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.presidency.models.PresidencyModel.pres_url, verbose_name='Foto')),
            ],
        ),
    ]
